# Generated by Django 5.2.5 on 2025-08-13 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilosophySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Philosophy School',
                'verbose_name_plural': 'Philosophy Schools',
            },
        ),
        migrations.CreateModel(
            name='Philosopher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('works', models.TextField(blank=True, help_text='Key works separated by commas')),
                ('key_ideas', models.TextField(blank=True, help_text='Key ideas separated by commas')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='URL to animated image (GIF/SVG)')),
                ('schools', models.ManyToManyField(blank=True, to='philosophers.philosophyschool')),
            ],
            options={
                'verbose_name': 'Philosopher',
                'verbose_name_plural': 'Philosophers',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True)),
                ('favorite_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='philosophers.philosophyschool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
